name: 签到 # yml文件名
 
on:
  workflow_dispatch:
  schedule:   
    # https://crontab.guru/
    # UTC 时间，中国时区应减 8
    #         ┌────────── minute (0 - 59)
    #         │ ┌──────── hour (0 - 23)
    #         │ │ ┌────── day of the month (1 - 31)
    #         │ │ │ ┌──── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌── day of the week (0 - 6 or SUN-SAT)
    #         │ │ │ │ │
    - cron: '0 1 * * *'
 
jobs:
  run-check-in: # 任务名
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: 运行签到
        run: python ./test.py
        env:
          USERWXMINITOKEN: ${{ secrets.XYBQD }}
